// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xblombwqslecowkngiac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibG9tYndxc2xlY293a25naWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MDU5NjUsImV4cCI6MjA4NzM4MTk2NX0.4z8y4oYdiyRhsJtoG2EJ2F0QZR5VW5fKg-CUvtJyfeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});